/** Common ISO 4217 codes for workspace money display. */
export const CURRENCY_OPTIONS: { value: string; label: string }[] = [
  { value: 'USD', label: 'USD — US dollar' },
  { value: 'EUR', label: 'EUR — Euro' },
  { value: 'GBP', label: 'GBP — British pound' },
  { value: 'JPY', label: 'JPY — Japanese yen' },
  { value: 'CNY', label: 'CNY — Chinese yuan' },
  { value: 'INR', label: 'INR — Indian rupee' },
  { value: 'AUD', label: 'AUD — Australian dollar' },
  { value: 'CAD', label: 'CAD — Canadian dollar' },
  { value: 'CHF', label: 'CHF — Swiss franc' },
  { value: 'SEK', label: 'SEK — Swedish krona' },
  { value: 'NOK', label: 'NOK — Norwegian krone' },
  { value: 'DKK', label: 'DKK — Danish krone' },
  { value: 'NZD', label: 'NZD — New Zealand dollar' },
  { value: 'SGD', label: 'SGD — Singapore dollar' },
  { value: 'HKD', label: 'HKD — Hong Kong dollar' },
  { value: 'KRW', label: 'KRW — South Korean won' },
  { value: 'MXN', label: 'MXN — Mexican peso' },
  { value: 'BRL', label: 'BRL — Brazilian real' },
  { value: 'ZAR', label: 'ZAR — South African rand' },
  { value: 'TRY', label: 'TRY — Turkish lira' },
  { value: 'PLN', label: 'PLN — Polish złoty' },
  { value: 'CZK', label: 'CZK — Czech koruna' },
  { value: 'HUF', label: 'HUF — Hungarian forint' },
  { value: 'ILS', label: 'ILS — Israeli shekel' },
  { value: 'AED', label: 'AED — UAE dirham' },
  { value: 'SAR', label: 'SAR — Saudi riyal' },
  { value: 'PHP', label: 'PHP — Philippine peso' },
  { value: 'THB', label: 'THB — Thai baht' },
  { value: 'IDR', label: 'IDR — Indonesian rupiah' },
  { value: 'MYR', label: 'MYR — Malaysian ringgit' },
  { value: 'CLP', label: 'CLP — Chilean peso' },
  { value: 'ARS', label: 'ARS — Argentine peso' },
  { value: 'COP', label: 'COP — Colombian peso' },
  { value: 'PEN', label: 'PEN — Peruvian sol' },
]

/** Locales that pair well with common regions (dates & number grouping). */
export const LOCALE_OPTIONS: { value: string; label: string }[] = [
  { value: 'en-US', label: 'English (United States)' },
  { value: 'en-GB', label: 'English (United Kingdom)' },
  { value: 'en-CA', label: 'English (Canada)' },
  { value: 'en-AU', label: 'English (Australia)' },
  { value: 'en-IN', label: 'English (India)' },
  { value: 'en-SG', label: 'English (Singapore)' },
  { value: 'de-DE', label: 'German (Germany)' },
  { value: 'de-AT', label: 'German (Austria)' },
  { value: 'de-CH', label: 'German (Switzerland)' },
  { value: 'fr-FR', label: 'French (France)' },
  { value: 'fr-CA', label: 'French (Canada)' },
  { value: 'fr-CH', label: 'French (Switzerland)' },
  { value: 'es-ES', label: 'Spanish (Spain)' },
  { value: 'es-MX', label: 'Spanish (Mexico)' },
  { value: 'es-AR', label: 'Spanish (Argentina)' },
  { value: 'pt-BR', label: 'Portuguese (Brazil)' },
  { value: 'pt-PT', label: 'Portuguese (Portugal)' },
  { value: 'it-IT', label: 'Italian (Italy)' },
  { value: 'nl-NL', label: 'Dutch (Netherlands)' },
  { value: 'nl-BE', label: 'Dutch (Belgium)' },
  { value: 'pl-PL', label: 'Polish (Poland)' },
  { value: 'sv-SE', label: 'Swedish (Sweden)' },
  { value: 'nb-NO', label: 'Norwegian (Norway)' },
  { value: 'da-DK', label: 'Danish (Denmark)' },
  { value: 'fi-FI', label: 'Finnish (Finland)' },
  { value: 'ja-JP', label: 'Japanese (Japan)' },
  { value: 'zh-CN', label: 'Chinese (China)' },
  { value: 'zh-TW', label: 'Chinese (Taiwan)' },
  { value: 'ko-KR', label: 'Korean (South Korea)' },
  { value: 'hi-IN', label: 'Hindi (India)' },
]

/** Frequently used IANA zones; full list available via `Intl.supportedValuesOf('timeZone')` in modern runtimes. */
export const TIMEZONE_OPTIONS: { value: string; label: string }[] = [
  { value: 'UTC', label: 'UTC' },
  { value: 'America/New_York', label: 'America — New York' },
  { value: 'America/Chicago', label: 'America — Chicago' },
  { value: 'America/Denver', label: 'America — Denver' },
  { value: 'America/Los_Angeles', label: 'America — Los Angeles' },
  { value: 'America/Phoenix', label: 'America — Phoenix' },
  { value: 'America/Toronto', label: 'America — Toronto' },
  { value: 'America/Vancouver', label: 'America — Vancouver' },
  { value: 'America/Mexico_City', label: 'America — Mexico City' },
  { value: 'America/Sao_Paulo', label: 'America — São Paulo' },
  { value: 'America/Buenos_Aires', label: 'America — Buenos Aires' },
  { value: 'Europe/London', label: 'Europe — London' },
  { value: 'Europe/Paris', label: 'Europe — Paris' },
  { value: 'Europe/Berlin', label: 'Europe — Berlin' },
  { value: 'Europe/Madrid', label: 'Europe — Madrid' },
  { value: 'Europe/Rome', label: 'Europe — Rome' },
  { value: 'Europe/Amsterdam', label: 'Europe — Amsterdam' },
  { value: 'Europe/Brussels', label: 'Europe — Brussels' },
  { value: 'Europe/Zurich', label: 'Europe — Zurich' },
  { value: 'Europe/Stockholm', label: 'Europe — Stockholm' },
  { value: 'Europe/Oslo', label: 'Europe — Oslo' },
  { value: 'Europe/Copenhagen', label: 'Europe — Copenhagen' },
  { value: 'Europe/Warsaw', label: 'Europe — Warsaw' },
  { value: 'Europe/Prague', label: 'Europe — Prague' },
  { value: 'Europe/Vienna', label: 'Europe — Vienna' },
  { value: 'Europe/Dublin', label: 'Europe — Dublin' },
  { value: 'Europe/Lisbon', label: 'Europe — Lisbon' },
  { value: 'Europe/Istanbul', label: 'Europe — Istanbul' },
  { value: 'Europe/Athens', label: 'Europe — Athens' },
  { value: 'Africa/Johannesburg', label: 'Africa — Johannesburg' },
  { value: 'Africa/Cairo', label: 'Africa — Cairo' },
  { value: 'Africa/Lagos', label: 'Africa — Lagos' },
  { value: 'Asia/Dubai', label: 'Asia — Dubai' },
  { value: 'Asia/Riyadh', label: 'Asia — Riyadh' },
  { value: 'Asia/Jerusalem', label: 'Asia — Jerusalem' },
  { value: 'Asia/Kolkata', label: 'Asia — Kolkata' },
  { value: 'Asia/Bangkok', label: 'Asia — Bangkok' },
  { value: 'Asia/Singapore', label: 'Asia — Singapore' },
  { value: 'Asia/Hong_Kong', label: 'Asia — Hong Kong' },
  { value: 'Asia/Shanghai', label: 'Asia — Shanghai' },
  { value: 'Asia/Tokyo', label: 'Asia — Tokyo' },
  { value: 'Asia/Seoul', label: 'Asia — Seoul' },
  { value: 'Asia/Manila', label: 'Asia — Manila' },
  { value: 'Asia/Jakarta', label: 'Asia — Jakarta' },
  { value: 'Australia/Sydney', label: 'Australia — Sydney' },
  { value: 'Australia/Melbourne', label: 'Australia — Melbourne' },
  { value: 'Australia/Perth', label: 'Australia — Perth' },
  { value: 'Pacific/Auckland', label: 'Pacific — Auckland' },
]
