services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: crm
      POSTGRES_PASSWORD: crm
      POSTGRES_DB: crm_manager
    ports:
      - '5432:5432'
    volumes:
      - crm_pg_data:/var/lib/postgresql/data

volumes:
  crm_pg_data:
