import type { Prisma } from '@prisma/client'
import { prisma } from '../lib/prisma.js'

/** Shape matches frontend `CrmState` for drop-in use */
export async function buildBootstrap(orgId: string, userId: string) {
  const membership = await prisma.membership.findUnique({
    where: { userId_organizationId: { userId, organizationId: orgId } },
    include: { user: { include: { preferences: true } } },
  })
  if (!membership) throw new Error('Not a member of this organization')

  const [
    members,
    teams,
    territories,
    tags,
    companies,
    contacts,
    leads,
    pipelines,
    deals,
    tasks,
    activities,
    emailLogs,
    calendarEvents,
    products,
    quotes,
    contracts,
    customFieldDefs,
    customFieldValues,
    boards,
    goals,
    sprints,
    documents,
    files,
    automations,
    emailSequences,
    webhooks,
    integrations,
    approvals,
    comments,
    notifications,
    inbox,
    forms,
    campaigns,
    tickets,
    surveys,
    auditLog,
    timeEntries,
  ] = await Promise.all([
    prisma.membership.findMany({
      where: { organizationId: orgId },
      include: { user: true },
    }),
    prisma.team.findMany({ where: { organizationId: orgId } }),
    prisma.territory.findMany({ where: { organizationId: orgId } }),
    prisma.tag.findMany({ where: { organizationId: orgId } }),
    prisma.company.findMany({ where: { organizationId: orgId } }),
    prisma.contact.findMany({
      where: { organizationId: orgId },
      include: { tags: true },
    }),
    prisma.lead.findMany({
      where: { organizationId: orgId },
      include: { tags: true },
    }),
    prisma.pipeline.findMany({
      where: { organizationId: orgId },
      include: { stages: { orderBy: { order: 'asc' } } },
    }),
    prisma.deal.findMany({
      where: { organizationId: orgId },
      include: { tags: true },
    }),
    prisma.task.findMany({ where: { organizationId: orgId } }),
    prisma.activity.findMany({
      where: { organizationId: orgId },
      orderBy: { at: 'desc' },
      take: 500,
    }),
    prisma.emailLog.findMany({
      where: { organizationId: orgId },
      orderBy: { sentAt: 'desc' },
      take: 200,
    }),
    prisma.calendarEvent.findMany({ where: { organizationId: orgId } }),
    prisma.product.findMany({ where: { organizationId: orgId } }),
    prisma.quote.findMany({ where: { organizationId: orgId } }),
    prisma.contract.findMany({ where: { organizationId: orgId } }),
    prisma.customFieldDef.findMany({ where: { organizationId: orgId } }),
    prisma.customFieldValue.findMany({
      where: { field: { organizationId: orgId } },
    }),
    prisma.board.findMany({
      where: { organizationId: orgId },
      include: { columns: true, items: true },
    }),
    prisma.goal.findMany({ where: { organizationId: orgId } }),
    prisma.sprint.findMany({ where: { organizationId: orgId } }),
    prisma.document.findMany({ where: { organizationId: orgId } }),
    prisma.fileAttachment.findMany({ where: { organizationId: orgId } }),
    prisma.automationRule.findMany({ where: { organizationId: orgId } }),
    prisma.emailSequence.findMany({ where: { organizationId: orgId } }),
    prisma.webhookEndpoint.findMany({ where: { organizationId: orgId } }),
    prisma.integrationConnection.findMany({ where: { organizationId: orgId } }),
    prisma.approval.findMany({ where: { organizationId: orgId } }),
    prisma.comment.findMany({
      where: { organizationId: orgId },
      orderBy: { createdAt: 'desc' },
      take: 500,
    }),
    prisma.notification.findMany({
      where: { userId },
      orderBy: { createdAt: 'desc' },
      take: 100,
    }),
    prisma.inboxMessage.findMany({ where: { organizationId: orgId } }),
    prisma.marketingForm.findMany({ where: { organizationId: orgId } }),
    prisma.campaign.findMany({ where: { organizationId: orgId } }),
    prisma.ticket.findMany({ where: { organizationId: orgId } }),
    prisma.survey.findMany({ where: { organizationId: orgId } }),
    prisma.auditLog.findMany({
      where: { organizationId: orgId },
      orderBy: { at: 'desc' },
      take: 200,
    }),
    prisma.timeEntry.findMany({
      where: { task: { organizationId: orgId } },
    }),
  ])

  const pipeline = pipelines[0]
  const pipelineStages = pipeline?.stages ?? []

  const cfValues: Record<string, Record<string, Record<string, unknown>>> = {}
  for (const v of customFieldValues) {
    const def = customFieldDefs.find((d) => d.id === v.fieldId)
    if (!def) continue
    const et = def.entityType
    if (!cfValues[et]) cfValues[et] = {}
    if (!cfValues[et][v.entityId]) cfValues[et][v.entityId] = {}
    cfValues[et][v.entityId][v.fieldId] = v.value
  }

  const prefs = membership.user.preferences

  return {
    version: 2,
    session: {
      userId: membership.user.id,
      email: membership.user.email,
      loggedInAt: new Date().toISOString(),
    },
    preferences: {
      theme: (prefs?.theme ?? 'system') as 'light' | 'dark' | 'system',
      emailDigest: prefs?.emailDigest ?? true,
      pushEnabled: prefs?.pushEnabled ?? true,
    },
    users: members.map((m) => ({
      id: m.user.id,
      name: m.user.name,
      email: m.user.email,
      role: m.role as 'admin' | 'manager' | 'rep' | 'guest' | 'readonly',
      teamId: m.teamId ?? teams[0]?.id ?? '',
      territoryId: m.territoryId,
      avatar: m.user.avatar ?? undefined,
    })),
    workspaces: [{ id: orgId, name: teams[0]?.workspaceName ?? 'Main workspace', isPrivate: false }],
    teams: teams.map((t) => ({ id: t.id, name: t.name, workspaceId: orgId })),
    territories: territories.map((t) => ({ id: t.id, name: t.name, userIds: t.userIds })),
    tags: tags.map((t) => ({ id: t.id, name: t.name, color: t.color })),
    companies: companies.map((c) => ({
      id: c.id,
      name: c.name,
      industry: c.industry,
      website: c.website,
      phone: c.phone,
      parentId: c.parentId,
      ownerId: c.ownerId,
      territoryId: c.territoryId,
      healthScore: c.healthScore,
      tagIds: [] as string[],
      createdAt: c.createdAt.toISOString(),
    })),
    contacts: contacts.map((c) => ({
      id: c.id,
      firstName: c.firstName,
      lastName: c.lastName,
      email: c.email,
      phone: c.phone,
      companyId: c.companyId,
      title: c.title,
      ownerId: c.ownerId,
      tagIds: c.tags.map((t) => t.tagId),
      leadId: c.leadId,
      createdAt: c.createdAt.toISOString(),
    })),
    leads: leads.map((l) => ({
      id: l.id,
      firstName: l.firstName,
      lastName: l.lastName,
      email: l.email,
      phone: l.phone,
      company: l.company,
      stage: l.stage as 'new' | 'contacted' | 'qualified' | 'converted' | 'disqualified',
      score: l.score,
      ownerId: l.ownerId,
      source: l.source,
      utmSource: l.utmSource,
      utmMedium: l.utmMedium,
      utmCampaign: l.utmCampaign,
      convertedContactId: l.convertedContactId,
      tagIds: l.tags.map((t) => t.tagId),
      createdAt: l.createdAt.toISOString(),
    })),
    pipelines: pipelines.map((p) => ({
      id: p.id,
      name: p.name,
      stageIds: p.stages.map((s) => s.id),
    })),
    pipelineStages: pipelineStages.map((s) => ({
      id: s.id,
      pipelineId: s.pipelineId,
      key: s.key as 'lead' | 'qualified' | 'proposal' | 'negotiation' | 'won' | 'lost',
      label: s.label,
      order: s.order,
      color: s.color,
      probability: s.probability,
    })),
    deals: deals.map((d) => ({
      id: d.id,
      title: d.title,
      value: d.value,
      stage: d.stageKey as 'lead' | 'qualified' | 'proposal' | 'negotiation' | 'won' | 'lost',
      pipelineId: d.pipelineId,
      contactId: d.contactId,
      companyId: d.companyId,
      ownerId: d.ownerId,
      expectedClose: d.expectedClose?.toISOString().slice(0, 10) ?? '',
      tagIds: d.tags.map((t) => t.tagId),
      slaDue: d.slaDue?.toISOString() ?? null,
      createdAt: d.createdAt.toISOString(),
    })),
    tasks: tasks.map((t) => ({
      id: t.id,
      title: t.title,
      description: t.description,
      dueDate: t.dueDate?.toISOString().slice(0, 10) ?? '',
      priority: t.priority as 'low' | 'medium' | 'high',
      status: t.status as 'todo' | 'in_progress' | 'done',
      contactId: t.contactId,
      dealId: t.dealId,
      ownerId: t.ownerId,
      parentId: t.parentId,
      dependsOn: t.dependsOn,
      recurring: t.recurring as 'none' | 'weekly' | 'monthly',
      estimateMinutes: t.estimateMinutes,
      loggedMinutes: t.loggedMinutes,
      sprintId: t.sprintId,
      goalId: t.goalId,
      checklist: (t.checklist as { id: string; text: string; done: boolean }[]) ?? [],
      tagIds: [] as string[],
      createdAt: t.createdAt.toISOString(),
    })),
    activities: activities.map((a) => ({
      id: a.id,
      type: a.type as 'call' | 'email' | 'meeting' | 'note',
      subject: a.subject,
      body: a.body,
      recordType: a.recordType,
      recordId: a.recordId,
      userId: a.userId,
      at: a.at.toISOString(),
    })),
    emailLogs: emailLogs.map((e) => ({
      id: e.id,
      recordType: e.recordType,
      recordId: e.recordId,
      to: e.to,
      subject: e.subject,
      body: e.body,
      userId: e.userId,
      sentAt: e.sentAt.toISOString(),
    })),
    calendarEvents: calendarEvents.map((e) => ({
      id: e.id,
      title: e.title,
      start: e.start.toISOString(),
      end: e.end.toISOString(),
      recordType: e.recordType,
      recordId: e.recordId,
      userId: e.userId,
      externalSync: e.externalSync as 'none' | 'google' | 'outlook',
    })),
    products: products.map((p) => ({
      id: p.id,
      name: p.name,
      sku: p.sku,
      price: p.price,
    })),
    quotes: quotes.map((q) => ({
      id: q.id,
      dealId: q.dealId,
      title: q.title,
      lines: q.lines as { productId: string; quantity: number; unitPrice: number }[],
      status: q.status as 'draft' | 'sent' | 'accepted' | 'rejected',
      createdAt: q.createdAt.toISOString(),
    })),
    contracts: contracts.map((c) => ({
      id: c.id,
      dealId: c.dealId,
      title: c.title,
      status: c.status as 'draft' | 'sent' | 'signed' | 'void',
      signUrl: c.signUrl,
      createdAt: c.createdAt.toISOString(),
    })),
    customFieldDefs: customFieldDefs.map((f) => ({
      id: f.id,
      entityType: f.entityType,
      label: f.label,
      type: f.type,
      options: f.options,
      formula: f.formula ?? undefined,
    })),
    customFieldValues: cfValues,
    segments: [],
    boards: boards.map((b) => ({
      id: b.id,
      name: b.name,
      workspaceId: orgId,
      columnIds: b.columns.map((c) => c.id),
      isPrivate: b.isPrivate,
    })),
    boardColumns: boards.flatMap((b) =>
      b.columns.map((c) => ({ id: c.id, boardId: b.id, title: c.title, order: c.order })),
    ),
    boardItems: boards.flatMap((b) =>
      b.items.map((i) => ({
        id: i.id,
        boardId: b.id,
        columnId: i.columnId,
        title: i.title,
        recordType: i.recordType,
        recordId: i.recordId,
        order: i.order,
        dueDate: i.dueDate?.toISOString().slice(0, 10) ?? null,
        ownerId: i.ownerId,
      })),
    ),
    timeEntries: timeEntries.map((e) => ({
      id: e.id,
      taskId: e.taskId,
      userId: e.userId,
      minutes: e.minutes,
      date: e.date.toISOString().slice(0, 10),
      note: e.note,
    })),
    goals: goals.map((g) => ({
      id: g.id,
      title: g.title,
      target: g.target,
      current: g.current,
      quarter: g.quarter,
      ownerId: g.ownerId,
    })),
    sprints: sprints.map((s) => ({
      id: s.id,
      name: s.name,
      start: s.start.toISOString().slice(0, 10),
      end: s.end.toISOString().slice(0, 10),
      teamId: s.teamId,
    })),
    documents: documents.map((d) => ({
      id: d.id,
      title: d.title,
      content: d.content,
      recordType: d.recordType,
      recordId: d.recordId,
      updatedAt: d.updatedAt.toISOString(),
    })),
    files: files.map((f) => ({
      id: f.id,
      recordType: f.recordType,
      recordId: f.recordId,
      name: f.name,
      size: f.size,
      mimeType: f.mimeType,
      uploadedAt: f.uploadedAt.toISOString(),
    })),
    automations: automations.map((a) => ({
      id: a.id,
      name: a.name,
      enabled: a.enabled,
      trigger: a.trigger as Prisma.JsonValue,
      actions: a.actions as Prisma.JsonValue,
    })),
    emailSequences: emailSequences.map((s) => ({
      id: s.id,
      name: s.name,
      steps: s.steps as { delayDays: number; subject: string; body: string }[],
      enabled: s.enabled,
    })),
    webhooks: webhooks.map((w) => ({
      id: w.id,
      url: w.url,
      events: w.events,
      enabled: w.enabled,
    })),
    integrations: integrations.map((i) => ({
      id: i.id,
      name: i.name,
      type: i.type as 'slack' | 'teams' | 'zapier' | 'make',
      enabled: i.enabled,
    })),
    approvals: approvals.map((a) => ({
      id: a.id,
      dealId: a.dealId,
      title: a.title,
      status: a.status as 'pending' | 'approved' | 'rejected',
      requesterId: a.requesterId,
      approverId: a.approverId,
      createdAt: a.createdAt.toISOString(),
    })),
    comments: comments.map((c) => ({
      id: c.id,
      recordType: c.recordType,
      recordId: c.recordId,
      userId: c.userId,
      body: c.body,
      mentions: c.mentions,
      createdAt: c.createdAt.toISOString(),
    })),
    notifications: notifications.map((n) => ({
      id: n.id,
      userId: n.userId,
      title: n.title,
      body: n.body,
      read: n.read,
      createdAt: n.createdAt.toISOString(),
    })),
    inbox: inbox.map((m) => ({
      id: m.id,
      teamId: m.teamId,
      from: m.from,
      subject: m.subject,
      body: m.body,
      read: m.read,
      receivedAt: m.receivedAt.toISOString(),
    })),
    forms: forms.map((f) => ({
      id: f.id,
      name: f.name,
      fields: f.fields as { id: string; label: string; type: string }[],
      submissions: f.submissions as { id: string; data: Record<string, string>; at: string }[],
    })),
    campaigns: campaigns.map((c) => ({
      id: c.id,
      name: c.name,
      utmSource: c.utmSource,
      utmMedium: c.utmMedium,
      budget: c.budget,
    })),
    tickets: tickets.map((t) => ({
      id: t.id,
      subject: t.subject,
      description: t.description,
      status: t.status as 'open' | 'pending' | 'resolved' | 'closed',
      priority: t.priority as 'low' | 'medium' | 'high',
      companyId: t.companyId,
      contactId: t.contactId,
      assigneeId: t.assigneeId,
      slaDue: t.slaDue?.toISOString() ?? null,
      createdAt: t.createdAt.toISOString(),
    })),
    surveys: surveys.map((s) => ({
      id: s.id,
      companyId: s.companyId,
      score: s.score,
      feedback: s.feedback,
      createdAt: s.createdAt.toISOString(),
    })),
    savedViews: [],
    auditLog: auditLog.map((a) => ({
      id: a.id,
      action: a.action,
      entityType: a.entityType,
      entityId: a.entityId,
      userId: a.userId,
      at: a.at.toISOString(),
    })),
  }
}
